Make compatible with latest VIM PowerShell support.
tpope/vim-fugitive pull request #1783
Opened 2021-07-03 15:08 UTC by mrdubya

PowerShell shell support has been improved as of VIM 8.2.3079 for Windows, MacOS, and Linux. This means that some changes are now required to work correctly.
Note that git status -bz under PowerShell appends a CR-LF pair which caused the summary buffer to always think there was 1 unnamed unstaged file and 1 unnamed staged file.

2021-07-04 05:52 UTC, tpope requested changes

2021-07-04 05:52 UTC, tpope commented on autoload/fugitive.vim
> +  elseif &shell =~# '\(powershell\|pwsh\)\(.exe\)\?$'
Let's change the pattern to `'\%(powershell\|pwsh\)\(\.exe\)\=$` to match my preferred styling and the operator to `=~?` because the `PowerShell` capitalization seems common.

2021-07-04 05:52 UTC, tpope commented on autoload/fugitive.vim
> +	  if len(sub)
Is that a hard tab?

2021-07-04 05:56 UTC, tpope commented
Thanks for this, and for the upstream Vim changes. After #1644 I peaked at the Vim source and was surprised to discover there wasn't even an _attempt_ to address PowerShell.

2021-07-04 10:28 UTC, mrdubya commented on autoload/fugitive.vim
> +  elseif &shell =~# '\(powershell\|pwsh\)\(.exe\)\?$'
No problem. Just found an issue with pwsh on Windows so a little more work needed.

2021-07-04 10:28 UTC, mrdubya commented on autoload/fugitive.vim
> +	  if len(sub)
Shucks, yes. It always slips through the cracks jumping across projects as to what and how they are enforced (e.g. use of modelines).

2021-07-04 10:53 UTC, mrdubya commented
I think most Windows users think invoking VIM from PowerShell results in using PowerShell as the shell from VIM. This is wrong, VIM will default to cmd.exe on Windows. Then again, using PowerShell as the shell in VIM is not a great environment as filters do not work, PowerShell does not support input redirection, at least not as most people expect it to work in a shell. But we digress.

2021-07-04 13:32 UTC, mrdubya commented
Some fun in TempCmd() - needed to craft a shell invocation to grab the redirected output, working around any existing redirected output from shellredir as happens with pwsh on Windows. Can't do it in SystemError() as that is used from elsewhere that can cope with the normal redirected output.

2021-07-04 13:49 UTC, tpope commented on autoload/fugitive.vim
> +  elseif &shell =~# '\(powershell\|pwsh\)\(.exe\)\?$'
Err, use `\%(` for the second `\(` too, I overlooked that.

2021-07-04 13:59 UTC, tpope commented on autoload/fugitive.vim
> +          if len(sub)
The fundamental problem is that `line` is empty? Let's change the `elseif line[0] !=# '#'` conditional to `elseif len(line) && line[0] !=# '#'` to more accurately convey what's going on (and greatly reduce the diff size to boot).

2021-07-04 14:01 UTC, tpope commented
My work-in-progress jobs branch already has `s:TempCmd()` re-implemented. So if that's the only sticking point, we can go ahead with merging this and I can escalate getting that piece of my branch merged in as well.

2021-07-04 14:04 UTC, tpope commented
Check the `job-temp-files` branch I just pushed if you want to verify that everything combined together works as expected.

2021-07-04 14:11 UTC, mrdubya commented on autoload/fugitive.vim
> +          if len(sub)
The line has a single character in it, LF. Do you want to handle the specific case or add in remaining line length check as well?

2021-07-04 14:22 UTC, mrdubya commented
Quick comment on your wip branch, `s:PrepareJob()` defaults to cmd.exe for win32 platforms. This gets into the realm of do you honor the users shell setting, or use a shell that should work regardless?

2021-07-04 14:26 UTC, tpope commented on autoload/fugitive.vim
> +          if len(sub)
That's a bit grosser, but `elseif line[0] =~# "[^#\n]"` or something similar seems like the way to go. Or clean it up at the source in `s:NullError()` if there's a natural way to do that. On that note, check that `:echo FugitiveConfig()` doesn't have any stray newlines, as that's the other big consumer of `s:NullError()`.

2021-07-04 14:29 UTC, tpope commented on autoload/fugitive.vim
> +          if len(sub)
It looks like Git commands with a `-z` flag always terminate with a final null byte, so just categorically stripping off a final `\n` seems safe.

2021-07-04 14:38 UTC, tpope commented on autoload/fugitive.vim
> +          if len(sub)
Scratch all of that, I fixed the hell out of this on master. You should be able to toss this hunk away and pull.

2021-07-04 14:40 UTC, tpope commented
That `cmd.exe` is only a fallback for older Git versions. And since implementing that I've made 1.8.5 mandatory so it can be ditched entirely.

2021-07-04 14:41 UTC, mrdubya commented on autoload/fugitive.vim
> +          if len(sub)
How about the following?
```
-        elseif line[0] !=# '#'
+        elseif line[0] !~# '[#[:space:]]'
````

2021-07-04 14:50 UTC, tpope commented on autoload/fugitive.vim
> +          if len(sub)
Great but my previous comment renders it moot.

2021-07-04 17:28 UTC, mrdubya commented
Ignore the merge please. I'll look into this some more the next few days.

2021-07-10 09:48 UTC, mrdubya commented
I have kicked the tyres with a merge of my changes and your `job-temp-files` branch and didn't seen any obvious problems. I'll run with it for the next week to see if anything pops up.

2021-07-10 13:27 UTC, tpope commented on autoload/fugitive.vim
> +        elseif line[0] !~# '[#[:space:]]'
Doesn't ae6f84adf3240e007f2be077d103781f65d4a437 render this unnecessary?

2021-07-10 13:52 UTC, mrdubya commented on autoload/fugitive.vim
> +        elseif line[0] !~# '[#[:space:]]'
It does, my fork was behind. An update and rebase removes it. With the reworking of `s:TempCmd()` the change comes down to just the one line change in `s:BuildEnvPrefix()`.

2021-07-10 15:15 UTC, tpope commented on autoload/fugitive.vim
> +        elseif line[0] !~# '[#[:space:]]'
So if we postpone merging my `s:TempCmd()` reworking, how well does this patch work on its own? Is _your_ change to `s:TempCmd()` adequate, or are there still problems?

2021-07-10 15:17 UTC, tpope commented on autoload/fugitive.vim
> +  elseif &shell =~? '\%(powershell\|pwsh\)\(\.exe\)\=$'
Please make this '\%(powershell\|pwsh\)\%(\.exe\)\=$'. I always favor `\%(` when possible for ease of reasoning. (My initial requested change overlooked the second capture group.)

2021-07-10 15:17 UTC, tpope commented on autoload/fugitive.vim
> +    elseif &shell =~? '\%(powershell\|pwsh\)\(\.exe\)\=$'
This one too.

2021-07-16 21:10 UTC, tpope commented on autoload/fugitive.vim
> +        elseif line[0] !~# '[#[:space:]]'
Let me ask a simpler question: Is there any reason not to go ahead and merge this? If it's a step in the right direction, I'd rather go ahead and get it in, even if there are caveats.

2021-07-24 11:28 UTC, merged

2021-07-24 14:12 UTC, mrdubya commented on autoload/fugitive.vim
> +        elseif line[0] !~# '[#[:space:]]'
Apologies, it has been a busy week for me. Yes, without your `s:TempCmd()` reworking my patch was adequate.  Thanks for merging the change.